### ISSUE TITLE
Reproducing figure in JOSS paper

### ISSUE THREAD

**Issue by matt-graham** [Simulation-Decomposition/simdec-python#34]
Raising as part of JOSS review openjournals/joss-reviews/issues/6713

It would be nice if code was provided (even better if it was in the paper as an example usage) for reproducing the plot / table shown in Figure 1 in the paper, along with some description of the data used to produce it and how to access.

**Comment by tupui** [comment]
I would not do that in the paper. APIs tend to change and I would not want people to copy past something from a paper that we cannot easily update.

The figure was more of showcase not meant to be analysed by the reader, since the paper is less about the method and more about the code. i.e. we managed to make something pretty which is meaningful.

But if you really want, we can add a description.

Otherwise I would close this issue in favour #31 where you ask for an example in the doc itself, which we can run in the CI and update as we go.

**Comment by matt-graham** [comment]
In terms of APIs changing - while a good point, there are ways that could be dealt with, for example specifying the version of the package used if providing code in the paper or providing a permalink to a script in the repository at a specific commit. The reviewer checklist asks us to confirm that 'If the paper contains original results, results are entirely reproducible by reviewers' which at the moment I judged not to be the case, hence this issue. 

I would say some form of description of what the figure is showing and the provenance of the data being visualized is a minimum requirement for the figure to be useful to a reader. At the moment from the current paper alone I struggled to understand what the figure was showing. Alternatively there is no requirement to include any figures so it could be removed, but I do think having an example output to help the reader understand what the package can do is helpful.

**Comment by tupui** [comment]
@matt-graham I added an executable notebook in the doc, see #23

<img width="1462" alt="Screenshot 2024-05-30 at 11 31 01" src="https://github.com/Simulation-Decomposition/simdec-python/assets/23188539/52bc90da-0408-4f4b-98cb-713034081c2c">
<img width="1559" alt="Screenshot 2024-05-30 at 11 31 12" src="https://github.com/Simulation-Decomposition/simdec-python/assets/23188539/a724939b-0547-4933-885e-d95081b0b005">

**Comment by matt-graham** [comment]
Thanks this looks great.
